# Generated by Django 5.1.2 on 2025-07-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fees_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
