# Generated by Django 5.1.2 on 2025-07-20 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_fees_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('attendance', models.FloatField(default=0.0, max_length=10)),
                ('marks', models.FloatField(default=0.0, max_length=10)),
                ('year', models.IntegerField(blank=True, default=True, max_length=10)),
                ('fees_amount', models.IntegerField(max_length=20)),
                ('receipt', models.FileField(upload_to='receipts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
