# Generated by Django 5.1.2 on 2025-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('registrar', 'registrar'), ('admin', 'admin')], default='student', max_length=20),
        ),
    ]
