# Generated by Django 5.1.2 on 2025-07-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
