# Generated by Django 5.1.2 on 2025-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_num',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
    ]
