# Generated by Django 5.1.2 on 2025-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_phone_num_alter_student_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
