# Generated by Django 5.1.2 on 2025-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default='', max_length=2),
        ),
    ]
