# Generated by Django 5.1.2 on 2025-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
