# Generated by Django 5.1.2 on 2025-07-22 11:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_student_profile_alter_student_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
    ]
