# Generated by Django 5.1.2 on 2025-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='meesage',
            field=models.TextField(default=''),
        ),
    ]
