# Generated by Django 5.1.2 on 2025-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notes_meesage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='meesage',
            new_name='message',
        ),
    ]
