# Generated by Django 5.1.2 on 2025-07-22 16:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_meesage_notes_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
    ]
