# Generated by Django 5.1.2 on 2025-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_teacher_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='roles',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
