# Generated by Django 5.1.2 on 2025-07-22 19:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_new_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
        migrations.DeleteModel(
            name='new_admin',
        ),
    ]
