# Generated by Django 5.1.2 on 2025-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_student_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='subject',
        ),
        migrations.AddField(
            model_name='student_submission',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
