# Generated by Django 5.1.2 on 2025-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_announcement_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
