# Generated by Django 5.1.2 on 2025-07-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_announcement_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='subject',
        ),
    ]
